services:
  upm:
    image: docker.io/verdaccio/verdaccio
    container_name: upm
    user: 1000:1000
    ports:
      - 4873:4873
    volumes:
      - ./conf:/verdaccio/conf
      - ./storage:/verdaccio/storage
      - ./plugins:/verdaccio/plugins
    restart: unless-stopped
