services:
  upm:
    build: .
    image: upm
    container_name: upm
    env_file:
      - .env
    ports:
      - 4873:4873
    volumes:
      - upm_data:/verdaccio/storage
    restart: unless-stopped

volumes:
  upm_data:
