storage: /verdaccio/storage/data

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
    max_users: -1

security:
  api:
    jwt:
      sign:
        expiresIn: 30d
  web:
    sign:
      expiresIn: 7d

uplinks:
  OpenUPM:
    url: https://package.openupm.com/
  UnityNuGet:
    url: https://unitynuget-registry.openupm.com/

packages:
  'org.nuget.*':
    access: $all
    publish: $authenticated
    proxy: UnityNuGet
  '*':
    access: $all
    publish: $authenticated
    proxy: OpenUPM
