storage: /verdaccio/storage/data

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
    max_users: -1

uplinks:
  OpenUPM:
    url: https://package.openupm.com/
  UnityNuGet:
    url: https://unitynuget-registry.openupm.com/

packages:
  'org.nuget.*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: UnityNuGet
  '*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: OpenUPM
